name: Extract and Upload to Google Drive

on:
  workflow_dispatch: # Memungkinkan workflow dijalankan secara manual
    inputs:
      file_urls:
        description: "Daftar URL file RAR/ZIP yang akan diunduh (dipisahkan dengan koma)"
        required: true

jobs:
  extract_and_upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install rarfile google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2
          sudo apt-get update
          sudo apt-get install -y unrar unzip  # Install unrar dan unzip

      # Create token.pickle from secret
      - name: Create token.pickle
        run: |
          echo "${{ secrets.GDRIVE_TOKEN }}" | base64 --decode > token.pickle

      # Download files from URLs
      - name: Download files
        run: |
          IFS=',' read -r -a urls <<< "${{ inputs.file_urls }}"
          for url in "${urls[@]}"; do
            wget "$url" -O "$(basename "$url")"
          done

      # Ekstrak file RAR/ZIP
      - name: Extract RAR/ZIP files
        run: |
          for file in *.rar *.zip; do
            if [ -e "$file" ]; then
              echo "Processing $file..."
              if [[ "$file" == *.rar ]]; then
                echo "Extracting $file as RAR..."
                unrar x -y "$file" || echo "$file is not a valid archive. Skipping..."
              elif [[ "$file" == *.zip ]]; then
                echo "Extracting $file as ZIP..."
                unzip -o "$file" || echo "$file is not a valid archive. Skipping..."
              else
                echo "$file is not a valid archive format. Skipping..."
              fi
              rm -f "$file" || echo "Failed to delete $file. Skipping..."
            else
              echo "No files found matching pattern: $file"
            fi
          done

      # Jalankan script Python untuk upload ke Google Drive
      - name: Extract and upload to Google Drive
        run: |
          python3 script.py
